Repository codemaniac-sahil/dictionary-web-app, pull requests merged in 2022-10, with the labels that each got.

#12 Fixed the search bar UI
  index.html
  script.js
  style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 added a fix to handle invalid words
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#18 Added loading spinner and some CSS
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 Enhancement and Fixes
  assets/sound-svgrepo-com.svg
  index.html
  src/script.js
  styles/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#30 made responsive and improved ui
  index.html
  src/script.js
  styles/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#29 added css animation #28
  styles/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#32 Added spellcheck to searchbar
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#33 Modified color scheme and styles, Documentation updated.
  README.md
  index.html
  src/script.js
  styles/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#35 Modified Color Scheme, UX
  index.html
  src/script.js
  styles/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#38 #37 Alert message added to script file
  index.html
  src/script.js
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#55 Mobile UI Fixed
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#56 Added Glasseffect CSS to the div
  index.html
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#63 moved main div to center and changed some basic css to make website m…
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#69 made example interjection capital
  src/script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#72 added scroll bar
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#73 fix example
  src/script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#75 Adds dark mode
  assets/sound-svgrepo-com.svg
  index.html
  src/script.js
  styles/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
